name: Nightly

on: 
  workflow_dispatch:
  schedule:
    - cron: "13 01 * * *"

permissions:
  contents: write
  actions: write

jobs:
  check:
    name: Pre-check
    runs-on: 'ubuntu-latest'
    steps:
    - uses: octokit/request-action@v2.x
      id: check_last_run
      with:
        route: GET /repos/${{github.repository}}/actions/workflows/nightly.yml/runs?per_page=1&status=completed
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - run: |
        echo Last nightly commit: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha }}
        echo Current run commit:  ${{ github.sha }}
        echo Should run: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha != github.sha }}

    - if: ${{ fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha == github.sha }}
      run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}
      env:
        GH_TOKEN: ${{ github.token }}

  build:
    name: Build
    needs: [check]
    uses: ./.github/workflows/reusable-build.yml
    strategy:
      fail-fast: false
      matrix:
        architecture: [x64, x86]
    with:
      architecture: ${{ matrix.architecture }}
      upload: true
        
  publish:
    name: Package
    needs: [build]
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Re-arrange artifacts
        shell: cmd
        run: |
          dir /S /B
          move Orbiter-x64\Orbiter.zip Orbiter-x64.zip
          move Orbiter-x86\Orbiter.zip Orbiter-x86.zip
          dir /S /B

      - name: "Create nightly release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Orbiter development build"
          files: |
            Orbiter-x86.zip
            Orbiter-x64.zip
