name: Update Linux branch
on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  update:
    name: Update 'linux' branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: linux
      - name: Update branch
        run: |
          git checkout linux
          git merge origin/main --no-edit -m "Merged main branch on $(date +%F)"
          git push origin linux
  
